#! /bin/sh
set -e
in=${1:?"Usage: adddate <fromfile> <tofile>"}
out=${2:?"Usage: adddate <fromfile> <tofile>"}

date=$(strings ${in} | egrep "^[0-9][0-9][0-9][0-9]-[0-9][0-9]" | tail -1)
if [ -z "${date}" ]; then
	echo "Unable to add date to ${tofile} - run exiftool yourself."
	exit 0
fi
exiftool -P -CreateDate="${date}" ${out}
mv ${in} ${date}.mov
mv ${out} ${date}.jpg
rm ${out}_original
