#! /bin/sh

file="${1:?"Usage: $0 mov [v|h]"}"
orientation="${2:?"Usage: $0 mov [v|h|s]"}"
loop="${3}"

o="640x480"
gif="${file%%.*}".gif

if [ -z "${loop}" ]; then
	noloop="--no-loopcount"
fi

if [ x"${orientation}" = x"v" ]; then
	o="480x640"
elif [ x"${orientation}" = x"s" ]; then
	o="480x480"
fi

ffmpeg -i "${file}" -s "${o}" -pix_fmt rgb24 -r 10 -f gif - | \
	gifsicle --optimize=3 --delay=10  ${noloop} > "${gif}"

date=$(strings "${file}" | egrep 20[0-9][0-9] | tail -1)

if [ -n "${date}" ]; then
	exiftool -P -CreateDate="${date}" "${gif}" && \
		rm -f "${gif}_original"
fi
