#! /bin/sh

file="${1:?"Usage: $0 mov [v|h|s] [resolution] [loop]"}"
orientation="${2:?"Usage: $0 mov [v|h|s] [resolution] [loop]"}"
resolution="${3}"
loop="${4}"

if [ -z "${3}" ]; then
	o="640x480"
else
	o="${resolution}"
fi

gif="${file%%.*}".gif

if [ -z "${loop}" ]; then
	noloop="--no-loopcount"
fi

if [ x"${orientation}" = x"v" ]; then
	if [ -z "${3}" ]; then
		o="480x640"
	fi
elif [ x"${orientation}" = x"s" ]; then
	if [ -z "${3}" ]; then
		o="480x480"
	fi
fi

ffmpeg -i "${file}" -s "${o}" -pix_fmt rgb24 -r 10 -f gif - | \
	gifsicle --optimize=3 --delay=10  ${noloop} > "${gif}"

date=$(strings "${file}" | egrep 20[0-9][0-9] | tail -1)

if [ -n "${date}" ]; then
	exiftool -P -CreateDate="${date}" "${gif}" && \
		rm -f "${gif}_original"
	date="$( echo "${date}" | sed -e 's/:/-/g' -e 's/[+-][0-9][0-9][0-9][0-9]//' )"
	mv "${gif}" "${date}.gif"
fi
