#!/bin/sh
#set -e

#for file in *.m4v *mov *MOV; do
for file in *MOV; do
	prefix="${file%%.MOV}"
	prefix="${prefix%%.mov}"
	prefix="${prefix%%.m4v}"
	jpg=${prefix}.jpg
	ffmpeg -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg
	mv 1.jpg ${jpg}
	mv ${file} 1.MOV
	#ffmpeg -i 1.MOV -c:a copy -vf scale=iw/2:-1 0.MOV
	ffmpeg -i 1.MOV -c:a copy -vf scale=640:-1 -vcodec libtheora -acodec libvorbis -qscale:v 8 -qscale:a 8 small.ogv
	mv small.ogv ${prefix}-small.ogv
	mv 1.MOV ${file}

	date=$(strings ${file} | egrep "^[0-9][0-9][0-9][0-9]-[0-9][0-9]" | tail -1)
	if [ -z "${date}" ]; then
		echo "Unable to add date to ${jpg} - run exiftool yourself."
	else
		exiftool -P -CreateDate="${date}" ${jpg}
		mv ${prefix}.ogv ${date}.ogv
		mv ${prefix}-small.ogv ${date}-small.ogv
		mv ${jpg} ${date}.jpg
		rm ${jpg}_original
	fi

	#convert -rotate 180 ${jpg} 1.jpg && mv 1.jpg ${jpg}
done

# mp4 are vine's, so short and small
for file in *.mp4; do
	if [ ! -e ${file} ]; then
		continue
	fi
	prefix="${file%%.mp4}"
	jpg=${prefix}.jpg
	ffmpeg -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg
	mv 1.jpg ${jpg}
	ffmpeg -i ${file} -vcodec libtheora -acodec libvorbis -qscale:v 10 -qscale:a 10 ${prefix}.ogv
	~/bin/adddate ${file} ${jpg}
done
