#!/bin/sh
set -e

DONT=""
TSONLY=0

gififyIfLivePic() {
	local readonly file="${1}"
	local duration
	local rotation
	local scale 

	local h="640"
	local v="480"
	local orientation="h"

	if [ ${TSONLY} -gt 0 ]; then
		return 1
	fi

	echo "==> Checking if '${file}' is a live pic..."

	duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -i "${file}" | awk -F. '{print $1}')

	if [ "${duration}" -gt 10 ]; then
		echo "==> Not going to gifify ${duration}s long '${file}'."
		return 1
	fi

	scale=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 -i "${file}" | sed -e 's/x/\//' -e 's/x$//' | head -1 | bc -l)

	rotation=$(ffprobe -v error -select_streams v:0 -show_entries stream -of default=noprint_wrappers=1 -i "${file}" | sed -n -e 's/^rotation=-*//p')

	if [ x"${rotation}" = x"90" ]; then
		v="${h}"
		h="$(echo ${h}/${scale} | bc)"
		orientation="v"
	else
		v="$(echo ${h}/${scale} | bc)"
	fi


	echo "==> Turning '${file}' into a gif..."
	${DONT} livegif "${file}" "${orientation}" "${h}x${v}"
	${DONT} mv "${file}" .livepics

	return 0
}

createScreenshot() {
	file="${1}"
	jpg="${jpg}"
	echo "==> Grabbing screenshot from ${file}..."
	${DONT} ffmpeg -loglevel error -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg 2>/dev/null
	${DONT} mv 1.jpg ${jpg}
}

resizeMovie() {
	file="${1}"
	prefix="${2}"

	echo "==> Resizing ${file}..."
	${DONT} mv ${file} 1.MOV
	#${DONT} ffmpeg -loglevel error -i 1.MOV -c:a copy -vf scale=640:-1 -vcodec libtheora -acodec libvorbis -qscale:v 8 -qscale:a 8 -max_muxing_queue_size 9999 small.ogv
	${DONT} ffmpeg -loglevel error -i 1.MOV -vf scale=640:-1 -b:v 0 -crf 30 -pass 1 -an -f webm -y /dev/null
	${DONT} ffmpeg -loglevel error -i 1.MOV -vf scale=640:-1 -b:v 0 -crf 30 -pass 2 small.webm
	${DONT} mv small.webm ${prefix}-small.webm
	${DONT} mv 1.MOV ${file}
	${DONT} rm -f ffmpeg2pass-0.log
}

renameByDate() {
	file="${1}"
	prefix="${2}"
	jpg="${3}"

	suffix="${file##*.}"
	date=$(strings ${file} | egrep "^[0-9][0-9][0-9][0-9]-[0-9][0-9]" | tail -1)
	if [ -z "${date}" ]; then
		echo "Unable to add date to ${jpg} - run exiftool yourself."
	else
		echo "==> Adding a date ${date} to ${jpg}..."
		${DONT} exiftool -P -CreateDate="${date}" ${jpg} 2>/dev/null
		date="$( echo "${date}" | sed -e 's/:/-/g' -e 's/[+-][0-9][0-9][0-9][0-9]//' )"
		${DONT} mv ${file} ${date}.${suffix}
		if [ -f ${prefix}-small.ogv ]; then
			${DONT} mv ${prefix}-small.ogv ${date}-small.ogv
		fi
		if [ -f ${jpg} ]; then
			${DONT} mv ${jpg} ${date}.jpg
		fi
		if [ -f ${jpg}_original ]; then
			${DONT} rm ${jpg}_original
		fi
	fi
}


handleMp4() {
	file="${1}"

	if [ ! -e ${file} ]; then
		continue
	fi
	echo "=> Preparing ${file}..."
	prefix="${file%%.mp4}"
	jpg=${prefix}.jpg
	${DONT} ffmpeg -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg
	${DONT} mv 1.jpg ${jpg}
	${DONT} ffmpeg -i ${file} -vcodec libtheora -acodec libvorbis -qscale:v 10 -qscale:a 10 ${prefix}.ogv
	${DONT} ~/bin/adddate ${file} ${jpg}
}

usage() {
	cat <<EOH
Usage: ${PROGNAME} [-dht]
        -d  don't do anything; just echo what would be done
        -h  print this help and exit
        -t  timestamp files only
EOH
}

while getopts 'dht' opt; do
	case "${opt}" in
		d)
			DONT="echo "
			;;
		h|\?)
			usage
			exit 0
			# NOTREACHED
			;;
		t)
			TSONLY=1
			;;
		*)
			usage
			exit 1
			# NOTREACHED
	esac
done

#for file in *MOV; do
#for file in $(ls *mov | grep -v -- -); do

mkdir -p .livepics

for file in *.m4v *mov *MOV; do
	if [ ! -e "${file}" ]; then
		continue
	fi
	echo "=> Preparing ${file}..."

	if gififyIfLivePic "${file}" ; then
		continue
	fi

	prefix="${file%%.MOV}"
	prefix="${prefix%%.mov}"
	prefix="${prefix%%.m4v}"
	jpg=${prefix}.jpg

	if [ ${TSONLY} -lt 1 ]; then
		createScreenshot "${file}" "${jpg}"
		resizeMovie "${file}" "${prefix}"
	fi
	renameByDate "${file}" "${prefix}" "${jpg}"

	#convert -rotate 180 ${jpg} 1.jpg && mv 1.jpg ${jpg}
done

# mp4 are vine's, so short and small
for file in *.mp4; do
	handleMp4 "${file}"
done
